apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-gin-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-gin-app
  template:
    metadata:
      labels:
        app: go-gin-app
    spec:
      containers:
      - name: go-gin-app
        image: gcr.io/ibupedia-project-2019/go-gin-app:v1
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health-check
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3